library(sqldf)
pc <- read.csv.sql("household_power_consumption.txt","select * from file where Date='1/2/2007' OR Date='2/2/2007' ",sep=";")
#pc <- read.csv("household_power_consumption_filtered2.txt",sep=";")
library(lubridate)
png(file="plot2.png",width = 480, height=480)
pc$Dtstr <- paste(pc$Date, pc$Time)
pc$Date2 <- parse_date_time(pc$Dtstr,"dmy hms")
plot(pc$Global_active_power ~ pc$Date2, type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()